version: '3.8'
services:
  service-db:
    container_name: my-travel-db
    image: postgres:16.1-bookworm
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - .:/docker-entrypoint-initdb.d
      - mytravel-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U taras -d my-travel']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - mytravel-network

  service-be:
    container_name: my-travel-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - service-db
      - redis
    networks:
      - mytravel-network

  pgadmin:
    container_name: my-travel-pgadmin
    image: dpage/pgadmin4:7.2
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - mytravel-network

  redis:
    container_name: my-travel-redis
    image: redis:7.2
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - mytravel-network

volumes:
  mytravel-db-data:
  pgadmin-data:
  redis-data:
networks:
  mytravel-network:
    driver: bridge
