FROM node:21-alpine3.18

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install && npm cache clean --force

COPY . .

RUN npm run build

EXPOSE 3000

# CMD ["npm", "run", "start:dev"]

CMD ["npm", "run", "start:prod"]