export const {
  PORT = 3000,
  NODE_ENV = 'development',
  APP_ENV = 'development',
  APP_SECRET = 'APP_SECRET',
  APOLLO_KEY = 'APOLLO_KEY',
  APP_AUTH_SECRET = 'APP_AUTH_SECRET',
  APP_REFRESH_SECRET = 'APP_REFRESH_SECRET',
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  WEB_URL = 'localhost:3001',
  MAILTRAP_USER = 'MAILTRAP_USER',
  MAILTRAP_PASS = 'MAILTRAP_PASS',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',
  ACCESS_TOKEN_PRIVATE_KEY = 'ACCESS_TOKEN_PRIVATE_KEY',
  ACCESS_TOKEN_PUBLIC_KEY = 'ACCESS_TOKEN_PUBLIC_KEY',
  REFRESH_TOKEN_PRIVATE_KEY = 'REFRESH_TOKEN_PRIVATE_KEY',
  REFRESH_TOKEN_PUBLIC_KEY = 'REFRESH_TOKEN_PUBLIC_KEY',
  ACCESS_TOKEN_EXPIRES = '60',
  REFRESH_TOKEN_EXPIRES = '720',
} = process.env;

export const IS_PRODUCTION = APP_ENV === 'production';

export const FULL_WEB_URL = `${
  IS_PRODUCTION ? 'https://' : 'http://'
}${WEB_URL}`;
